name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-test:
    name: Install and test the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install the package locally
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install dependencies for testing
      run: |
        pip install pytest-cov==3.0.0
        pip install black
    - name: Run unit tests and test the docs
      run: |
        pytest
    - name: Generate test coverage report from unit tests only
      run: |
        pytest tests --cov --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
    - name: Check code format
      run: |
        black --check .
