name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-test:
    name: Install and test the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install the package locally
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install dependencies for testing
      run: |
        pip install pytest
        pip install coverage
        pip install black
    - name: Generate test coverage report from unit tests
      run: |
        coverage run -m pytest 
        coverage report
        coverage xml
    - name: Test the docs and docstrings
      run: |
        pytest --doctest-modules --doctest-glob='*.rst'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
    - name: Check code format
      run: |
        black --check .
