name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-test:
    name: Install and test the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install the package locally
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install dependencies for testing
      run: |
        pip install pytest-cov
        pip install black
    - name: Generate coverage data
      run: |
        pytest tests --cov --cov-report xml
    - name: Test with pytest
      run: |
        pytest
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
#        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    - name: Check code format
      run: |
        black --check .
